const STRINGS = {
  ///TaxiApp Strings --
  create_ac: 'CREATE ACCOUNT',
  upcoming: 'UPCOMING',
  complete: 'COMPLETED',
  login: 'LOGIN',
  Next: 'NEXT',
  RateYourTrip: 'Rate Your Trip',
  ChatWithAdmin: 'Chat with Admin',
  ChatWithRider: 'Chat with Rider',
  TransactionHistory: 'Transaction History',
  Experirnce: 'How was Your Experience with',
  HelpAndFAQ: 'Help & FAQ',
  bankName: 'Bank Name',
  bankCode: 'Bank Code',
  Referralcodecopied: 'Referral code copied',
  RaiseTicket: 'Raise Ticket',
  GetTicket: 'Get ticket details',
  TicketStatus: 'Ticket Status',
  accountHolderName: 'Account Holder Name',
  accountNumber: 'Account Number',
  ibanNumber: 'IBAN Number Optional',
  CancelRide: 'CANCEL RIDE',
  Arrived: 'ARRIVED',
  STARTED: ' START RIDE',
  BankCode: 'BANK CODE',
  LetsCompleteDocumentation: 'LETS COMPLETE DOCUMENTATION',
  PleaseShareYourFeedback: 'Please share your feedback',
  add: 'ADD',
  CALL: 'CALL',
  ReferalCode: 'Referal Code',
  UsingSocialLogins:
    'You are registered with your social media account,change password is not applicable for social logins.',
  LOGOUT: 'LOGOUT',
  changePassword: 'Change Password',
  registration: 'registration',
  ALREDY_AC: 'Already have an account? ',
  BY_SIGN: 'By signing up, I accept the',
  AND: ' & ',
  editProfile: 'Edit Profile',
  home: 'Home',
  settings: 'Settings',
  myRide: 'My Ride',
  myEarnings: 'My Earnings',
  bonus: 'Bonus',
  documents: 'Documents',
  bankDetails: 'Bank Details',
  GoToLogin: 'GO TO LOGIN',
  Wallet: 'Wallet',
  submit: 'SUBMIT',
  AccountClose: 'Account Delete',
  Terms: 'Terms of use',
  Privacy: 'Privacy Policy',
  oneStep: 'Just one step away',
  getMoving: 'Get moving with ',
  Thankyou: 'Thank you for registering with Payride!',
  YourApplication:
    'Your application is under review. We will send you an email for next steps',
  payRide: 'PayRide',
  youWillRecieveOtpOn: 'You will recieve OTP on',
  dumyNumber: '+91 9876543210',
  email: 'Email',
  confirmPassword: 'Confirm Password',
  newPassword: 'New Password',
  oldPassword: 'Old Password',
  password: 'Password',
  userPassword: 'User Password',
  dontReceived: "Didn't Receieved? ",
  resend: 'Resend',
  forgotPassword: 'Forgot Password?',
  send: 'Send',
  que: '? ',
  GoToHome: 'HOME',
  clickHere: 'Click Here',
  singInWith: 'Sign in with',
  verticalSymbol: ' | ',
  beYourOwnBoss: 'Be Your own boss with PayRide',
  earnAmazing: 'Earn amazing rewards and bonuses',
  getMoreRides: 'Get more rides and qualify for a vacation trip',
  termsAndCondition: 'Terms of use',
  otpVerification: 'OTP Verification',
  pin1ref: 'pin1ref',
  pin2ref: 'pin2ref',
  pin3ref: 'pin3ref',
  pin4ref: 'pin4ref',
  totalRide: 'Total Ride : 52',
  bronze: 'Bronze',
  share: 'SHARE',
  rateTheApp: 'Rate the App',
  helpFAQ: 'Help & FAQ',
  support: 'Support',
  enterCurrentPassword: 'Enter your current password to create a new one',
  enterEmailadrsAssociated:
    'Enter your email address associated with your account.',
  selectCarImg: 'Upload Vehicle Image',
  dLicense: "Driver's license",
  daily: 'Daily',
  weekly: 'Weekly',
  monthly: 'Monthly',
  yearly: 'Yearly',
  ngCurrency: '₦',
  zeroAmnt: ' 0.00',
  rideListNoFound: 'Ride list no found',
  update: 'UPDATE',
  updateBankAccount: 'Change Bank Account',
  feelFree:
    'Please feel free to talk to us if you have any questions. We will endeavour to answer within 24 hours',
  Nmae: 'Name',
  MobileNumber: 'Mobile Number',
  ConfirmPassword: 'Confirm Password',
  IAgree: 'I agree to',
  Verify: 'Verify',
  PleaseEnterYourNamefirst: 'Please Enter Your Name first.',
  PleaseSelectVehicleImage: 'Please select vehicle image',
  PleaseSelectDriverLicenseImage: 'Please select driver license image',
  PleaseSelectVehicleRegistrationImage:
    'Please select vehicle registration image',
  PleaseSelectBrandName: 'Please select brand name',
  PleaseSelectModelName: 'Please select model name',
  PleaseSelectVehicleYear: 'Please select vehicle year',
  PleaseSelectCarColor: 'Please select car color',
  PleaseSelectPlateNumber: 'Please select plate number',
  PleaseSelectChassisNumber: 'Please select chassis number',
  PleaseEnterYourEmailfirst: 'Please enter email.',
  PleaseEnterYourPhoneNumberfirst: 'Please enter Your mobile number.',
  PleaseEnterYourPhoneNumberEightDigiits:
    'Please enter minimum 8 digit of mobile number.',
  WalletAmountIsLessThanEnteredAmount:
    'Wallet amount is less than entered amount.',
  PleaseEnterAValidAmount: 'Please enter a valid amount.',

  PleaseEnterValidEmailAddress: 'Please enter valid email.',
  PleaseEnterYourTitle: 'Please enter your title',
  PleaseEnterYourIssue: 'Please enter your issue',
  PleaseEnterAccountHolderName: 'Please enter account holder name',
  PleaseEnterBankCode: 'Please enter bank code',
  PleaseEnterAccountNumber: 'Please enter account number',
  PleaseEnterYourPassword: 'Please enter password',
  YourPasswordMustBeGreaterThanEghtDigit:
    'Your Password Must Be Greater Than EIght Digit.',
  PleaseEnterYourCONFIRMPassword: 'Please enter confirm password',
  PleaseEnterYourUserPassword: 'Please enter user password',
  PasswordMismatch: 'Password mismatch.',

  RememberMe: 'RememberMe',
  ExpiryDate: 'Expiry Date',
  Vehicle_Reg: 'Vehicle Registration',
  VehicleDetails: 'Vehicle Details',
  VehicleType: 'Vehicle Type',
  CarBrand: 'Car Brand (Eg Toyota)',
  Model: 'Model (Eg Corolla)',
  VehicleYear: 'Vehicle Year (eg 2016)',
  Color: 'Color (White)',
  Plate: 'Plate Number',
  Classis_Number: 'Classis Number',
  Title: 'Title',
  Issue: 'Your Issue / Problem',
  pick_up: 'Pick Up',
  drop_up: 'Drop Off',
  FareDetails: 'Fare Details',
  Ride_Type: 'Ride Type',
  Total_Distance: 'Total Distance',
  Time: 'Time',
  Payment_Type: 'Payment Type',
  Sub_Total: 'Sub Total',
  Tips: 'Tips',
  Total: 'Total',
  ChangePasswordText: 'Enter your current password to create a new one.',
  ChangeNewPasswordText: 'Enter your new password to change a new one.',

  current_Pass: 'Current Password',
  Ranking: 'Ranking',
  FillOtp: 'Please enter valid OTP',
  classis_number: 'Chassis Number',
  Payment_Mode: 'Payment Mode',
  PleaseClickOnEmoji: 'PleaseClickOnEmoji',
  InviteAFriend: 'Invite a Friend',
  Invitation:
    'Invite a friend and earn amazing discounts, bonuses and free rides!',
  EnterAmount: 'Enter amount',
  AddAmount: 'Add Amount',
  PayAmount: 'Pay Amount',
  SOSDistance: 'SOSDistance',
  SOSID: 'SOSID',
  LASTSOSLOCATION: 'LASTSOSLOCATION',
  LASTSOSLAT: 'LASTSOSLAT',
  LASTSOSLONG: 'LASTSOSLONG',
  SOSSTOPSENDING: 'SOSSTOPSENDING',
  FLOATICON: 'FLOATICON',
  FLOATING_ICON_ENABLE: 'FLOATING_ICON_ENABLE',
  PleaseEnterBankName: 'Please Enter Bank Name',
};

export default STRINGS;
